### PR TITLE
Feature/openapi doc

### PR DESCRIPTION
**Pull request by mgdaily**
This updates the theme of the OCS Github Pages site to `beautiful-jekyll-theme` which I have found to be a bit more easily customizable. 

Built API docs in the form of self-contained HTML files will be stored in the `docs/` directory. These doc files can be automatically updated by any of the OCS projects' GitHub actions.

Anytime a new project is added, we simply need to update the `_config.yml` file to add it to the navbar dropdown and link to the appropriate doc file pushed up by that project's GH Action.

I have an exact replica of this repo running on a test GH Pages page here: https://mgdaily.github.io/ocs-gh-pages/

Related downtime PR: https://github.com/observatorycontrolsystem/downtime/pull/25

We should merge this GH Pages PR first, then merge the downtime PR so that it pushes a fresh doc build to the live site.

### CODE REVIEW

**Review by eheinrich — APPROVED** [review]
Nice, looks good!

Is there any way to remove the "ocs-gh-pages" link from the top left corner?

**Review by jnation3406 — APPROVED** [review]
looks good

**Comment by mgdaily** [comment]
> Nice, looks good!
> 
> Is there any way to remove the "ocs-gh-pages" link from the top left corner?

Yes. I can set it to whatever we want. I just set it to "Observatory Control System" and it looks pretty good. Can also add images if we get a logo in the future :D

It's live at https://mgdaily.github.io/ocs-gh-pages/. Let me know what you prefer!

image

**Comment by eheinrich** [comment]
> Yes. I can set it to whatever we want. I just set it to "Observatory Control System" and it looks pretty good. Can also add images if we get a logo in the future :D
> 
> It's live at https://mgdaily.github.io/ocs-gh-pages/. Let me know what you prefer!

I like how it looks set to "Observatory Control System". Thanks!

**Pull request merged**
